const S = require('fluent-json-schema')

module.exports = S.object()
  .prop('DB_CLIENT', S.string()).required()
  .prop('DB_USER', S.string()).required()
  .prop('DB_PASSWORD', S.string()).required()
  .prop('DB_DATABASE', S.string().default('app')).required()
  .prop('DB_HOST', S.string()).required()
  .prop('JWT_SECRET', S.string()).required()
  .prop('PORT', S.number().default(3000))
  .prop('ORIGIN', S.string().default('localhost'))
  .prop('FILE_STORE_PROVIDER', S.string().default('local'))
  .prop('FILE_STORE_BASE_DIR', S.string().default('/tmp'))
  .prop('FILE_MAX_SIZE', S.number().default(10485760))
  .prop('SEED_ACCOUNT_EMAIL', S.string().default('seed@example.com'))
  .prop('SEED_ACCOUNT_PASSWORD', S.string().default('password'))
  .prop('SEED_ACCOUNT_DISPLAY_NAME', S.string().default('Seedy McSeederson'))
  .prop('SEED_ORGANIZATION_ABBREVIATION', S.string().default('SEED'))
  .prop('SEED_ORGANIZATION_NAME', S.string().default('Seeded Org.'))
  .prop('TEST_DB_CLIENT', S.string().default('sqlite3'))
  .prop('TEST_DB_FILENAME', S.string().default(':memory:'))
  .prop('TEST_DB_POOL_MIN', S.number().default(1))
  .prop('TEST_DB_POOL_MAX', S.number().default(1))
